# Generated by Django 2.0 on 2019-11-30 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('building_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('room_no', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('credit', models.IntegerField(default=0)),
                ('course_dept_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '课程信息',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_time', models.DateField(auto_now=True)),
                ('application_state', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectCourse.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField()),
                ('open_note_flag', models.BooleanField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectCourse.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('instructor_name', models.CharField(max_length=20)),
                ('instructor_password', models.CharField(max_length=20)),
                ('salary', models.IntegerField(default=0)),
                ('instructor_dept_name', models.CharField(max_length=20)),
                ('root_flag', models.BooleanField()),
            ],
            options={
                'verbose_name': '教师信息',
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='Instructor_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectCourse.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=0)),
                ('vacancy', models.IntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectCourse.Classroom')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectCourse.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=20)),
                ('student_password', models.CharField(max_length=20)),
                ('student_major', models.CharField(max_length=20)),
                ('student_dept_name', models.CharField(max_length=20)),
                ('student_total_credit', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '学生信息',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Student_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('grade', models.CharField(max_length=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectCourse.Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectCourse.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Time_slot',
            fields=[
                ('time_slot_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='time_slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectCourse.Time_slot'),
        ),
        migrations.AddField(
            model_name='instructor_section',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectCourse.Section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='selectCourse.Section'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectCourse.Student'),
        ),
    ]
