# Generated by Django 2.0 on 2019-12-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acount',
            fields=[
                ('id', models.TextField(db_column='ID', primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('role', models.IntegerField()),
            ],
            options={
                'db_table': 'acount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_no', models.TextField()),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'classroom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.TextField()),
                ('title', models.TextField()),
                ('credits', models.IntegerField()),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.TextField()),
                ('section_id', models.TextField()),
                ('day', models.IntegerField()),
                ('type', models.IntegerField()),
                ('start_time', models.TextField(blank=True, null=True)),
                ('end_time', models.TextField()),
                ('open_note_flag', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('type', models.IntegerField()),
                ('start_time', models.TextField(blank=True, null=True)),
                ('end_time', models.TextField()),
                ('open_note_flag', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam_old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.TextField(blank=True, null=True)),
                ('instructor_name', models.TextField(blank=True, null=True)),
                ('instructor_class', models.TextField(blank=True, null=True)),
                ('dept_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.IntegerField()),
                ('time', models.TextField()),
                ('classroom_no', models.TextField(blank=True, null=True)),
                ('lesson', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
            options={
                'db_table': 'section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectionOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.TextField()),
                ('title', models.TextField()),
                ('time', models.TextField()),
                ('classroom_no', models.TextField(blank=True, null=True)),
                ('lesson', models.IntegerField()),
                ('dept_name', models.TextField()),
                ('limit', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
            options={
                'db_table': 'section_old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.TextField()),
                ('student_name', models.TextField()),
                ('student_major', models.TextField()),
                ('student_dept_name', models.TextField()),
                ('student_total_credit', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.TextField()),
                ('section_id', models.IntegerField()),
                ('grade', models.TextField(blank=True, null=True)),
                ('drop_flag', models.IntegerField()),
            ],
            options={
                'db_table': 'takes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TakesOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_flag', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'takes_old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.TextField()),
                ('section_id', models.IntegerField()),
            ],
            options={
                'db_table': 'teaches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeachesOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'teaches_old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('end_time', models.IntegerField()),
                ('end_week', models.IntegerField()),
                ('start_week', models.IntegerField()),
                ('start_time', models.IntegerField()),
            ],
            options={
                'db_table': 'time',
                'managed': False,
            },
        ),
    ]
