# Generated by Django 2.0 on 2019-12-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectCourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'classroom'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'course'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'instructor'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'section'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student'},
        ),
        migrations.AlterModelOptions(
            name='time_slot',
            options={'verbose_name': 'time'},
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='building_name',
            new_name='classroom_no',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='vacancy',
            new_name='limit',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='time_slot',
            name='time_slot_id',
        ),
        migrations.AddField(
            model_name='instructor',
            name='instructor_class',
            field=models.CharField(default='讲师', max_length=20),
        ),
        migrations.AddField(
            model_name='time_slot',
            name='end_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='time_slot',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time_slot',
            name='start_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(default='第一学期', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='year',
            field=models.IntegerField(default='2017'),
        ),
        migrations.AlterField(
            model_name='time_slot',
            name='end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='time_slot',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='classroom',
            table='classroom',
        ),
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
        migrations.AlterModelTable(
            name='time_slot',
            table='time',
        ),
    ]
